language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  fast_finish: true
  include:
    - env: DM=~2.4
      php: 5.3
    - env: DM=~2.4
      php: 5.4
    - env: DM=~2.4@dev
      php: 5.5
    - env: DM=~2.4
      php: 5.6
    - env: DM=~2.4
      php: hhvm
    - env: DM=~2.4@dev
      php: hhvm-nightly
  exclude:
    - env: THENEEDFORTHIS=FAIL
  allow_failures:
    - php: hhvm-nightly

before_script:
  - composer require "wikibase/data-model=$DM" --prefer-source

script:
  - phpunit
  - phpunit --group slow

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikidata"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"
