language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  fast_finish: true
  include:
    - env: DM=~3.0
      php: 5.3
    - env: DM=~3.0
      php: 5.4
    - env: DM=~3.0@dev
      php: 5.6
    - env: DM=~3.0
      php: 7
    - env: DM=~3.0
      php: hhvm
    - env: DM=~3.0@dev
      php: hhvm-nightly
  exclude:
    - env: THENEEDFORTHIS=FAIL
  allow_failures:
    - php: hhvm-nightly

sudo: false

before_script:
  - travis_retry composer require "wikibase/data-model=$DM" --prefer-source

script: composer ci

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikidata"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"
